version: '3.9'

services:
  db-test:
    image: postgres:15.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parcels_test
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --username user --dbname=parcels_test']
      interval: 2s
      timeout: 5s
      retries: 5

  migrations-test:
    build:
      context: ./backend
      target: migrations
    environment:
      DB_HOST: db-test
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: parcels_test
    depends_on:
      db-test:
        condition: service_healthy
